name: "Multi event pipeline / workflow"  # Name of tghe pipeline

on:
    push:    # Event: whenever a push is made to the repository on the master / test branch
        branches:
            - master
            - test
    pull_request:  # Event whenever a pull request is made to the repository
        branches:
            - master


jobs:
    on-push: # job-1
        if: github.event_name == 'push' 
        runs-on: ubuntu-latest
        steps: # steps to be executed in the job
            - name: "Running on master / test push"   # step-1
              run: echo "running on master / test push"
    on-pull_request:  # job-2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in tha job
            - name: "Running on pull request" # step-2
              run: echo "Running on pull request"

